# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry below is written when the package is scaffolded with
# `benchmarks = true`, `ad = true`, or both (the BENCHMARKS_NAV substitution):
# a flat entry to the performance-history page for the benchmark suite alone,
# a flat entry to the kit-managed AD-comparison page alone, or both nested
# under one "Benchmarks" section when the package has both. A package with
# neither gets no entry and no page. The Tutorials entry is written only with
# `ad = true` (the AD_TUTORIALS_NAV substitution): it carries the kit-managed
# AD-backends page (which is which backends work and how to configure them;
# what each costs is the AD-comparison page above, under Benchmarks -- #299).
#
# Every entry must resolve to a page the package writes or `make.jl` generates.
# Docs about the kit itself (customising the generated site, how template sync
# keeps a repo current) live on the kit's own site, not on a package's (#194).

pages = [
    "Home" => "index.md",
    # Authored quickstart (a package-owned source page, distinct from the
    # README-derived home page). Add tutorials under `getting-started/` as the
    # package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md"{{AD_TUTORIALS_NAV}}
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ]{{BENCHMARKS_NAV}}
]
