# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry (BENCHMARKS_NAV) is written with `benchmarks = true`,
# `ad = true`, or both: its own top-level nav group under
# `docs/src/benchmarks/`, never nested inside Tutorials. Performance over
# time appears with `benchmarks = true`, the AD-comparison report with
# `ad = true`. The Tutorials entry (AD_TUTORIALS_NAV) is written only with
# `ad = true`, carrying the kit-managed AD-backends page.
#
# The Extensions group (EXTENSIONS_NAV) is written from whatever
# `[extensions]` the package declared at scaffold time, one entry per
# extension pointing at a page under `docs/src/extensions/`. Since this
# file is write-once, adding or removing an extension later means editing
# the group here too; a build drops any entry whose page is missing.
#
# Every entry must resolve to a page the package writes or `make.jl`
# generates. Docs about the kit itself live on the kit's own site (#194).

pages = [
    "Home" => "index.md",
    # Authored quickstart, distinct from the README-derived home page. Add
    # tutorials under `getting-started/` as the package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md"{{AD_TUTORIALS_NAV}},
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md",
    ],
    # Generated by `make.jl` from the repo's published GitHub releases; the
    # page degrades to a link when they cannot be fetched, so the entry is
    # always safe to keep.
    "Release notes" => "release-notes.md"{{EXTENSIONS_NAV}}{{BENCHMARKS_NAV}},
]
