# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. `make.jl` reads `pages` from this file; the API
# reference pages (lib/public.md, lib/internals.md) and the README-derived home
# page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    # Authored quickstart (package-owned source page, distinct from the
    # README-derived home page).
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Customising your docs" => "getting-started/customising.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    # Maintainer-facing reference: how the kit keeps itself (and adopters) to
    # the shared standard. Out of Getting started so it is not user-facing noise.
    "Development" => [
        "Infrastructure and template sync" => "getting-started/infrastructure.md",
        "Test infrastructure" => "getting-started/test-infrastructure.md",
        "Benchmarking" => "getting-started/benchmarking.md",
        "AD tooling" => "getting-started/ad-tooling.md"
    ]
]
