name: Documenter

on:
  push:
    branches: main
    tags: '*'
  pull_request:
  merge_group:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Documenter:
    uses: EpiAware/.github/.github/workflows/documentation.yml@0b92629d0e7663ba8708af5b4d2f8e03d05fea2c
    secrets: inherit  # pragma: allowlist secret
