name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    uses: EpiAware/.github/.github/workflows/format-check.yml@0b92629d0e7663ba8708af5b4d2f8e03d05fea2c
    secrets: inherit  # pragma: allowlist secret
